name: digia_expr
description: This library contains expressions that are used in digia_ui
version: 0.0.13
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# https://github.com/frencojobs/derry
scripts:
  i: flutter pub get
  build: dart run build_runner build --delete-conflicting-outputs
  clean:
    build:
      - flutter clean
      - rm -rf pubspec.lock
      - flutter pub get
      - $build
  format: dart format .
  fix: dart fix --apply
  lint: derry fix; derry format
  analyze: dart analyze
  analyse: derry analyze

# Add regular dependencies here.
dependencies:
  json_path: ^0.7.1
  moment_dart: ^2.1.0
  intl: ^0.19.0
  qs_dart: ^1.2.0
  collection: ^1.17.0

dev_dependencies:
  lints: 4.0.0
  test: ^1.21.0
